---
title: "Fitting Exercise"
format: html
---

# Introduction

We will explore and analyze data for the drug candidate **Mavoglurant**. These data were generated by the Metrum Research Group and can be accessed on Github through the following link: https://github.com/metrumresearchgroup/BayesPBPK-tutorial

# Load and clean the data

```{r}
# Load packages.
library(tidyverse)
library(tidymodels)
library(dplyr)
library(ggplot2)
library(here)

# Load the data and inspect.
data <- read_csv(here("Mavoglurant_A2121_nmpk.csv"))
glimpse(data)
```
```{r}
# Plot DV vs Time. Stratify by dose. 
ggplot(data, aes(x = TIME, y = DV, group = ID, color = factor(ID))) + # color by id 
    geom_line(alpha = 0.7) + 
    geom_point() + 
    facet_wrap(~ DOSE) + # stratified panels by dose 
    labs(
        title = "Drug Concentration vs. Time by Dose",
        x = "Time", 
        y = "DV (Drug Concentration)"
    ) + 
    theme_minimal() + 
    theme(legend.position = "none") # remove legend 
```
```{r}
# Keep only observations with OCC = 1 

data_occ1 <- data %>%
    filter(OCC == 1)

table(data_occ1$OCC)
```
```{r}
# Create a data frame that contains obly observations were TIME == 0. 
baseline_data <- data_occ1 %>%
    filter(TIME == 0)
dim(baseline_data)
```
```{r}
# Exclude observations with TIME = 0 and compute the sum of the DV cariable for each individual drug. Call this variable Y.

y_data <- data_occ1 %>%
    filter(TIME != 0) %>%
    group_by(ID) %>%
    summarize(Y = sum(DV, na.rm = TRUE))

dim(y_data)
```
```{r}
# Join the data sets and examine.
combined_data <- baseline_data %>%
    left_join(y_data, by = "ID") # adds Y to each subject while preserving the baseline rows 
dim(combined_data)
glimpse(combined_data)
```
```{r}
# Convert RACE and SEX to factors. Keep only Y, dose, age, sex, race, wt, and ht.

model_data <- combined_data %>%
    mutate(
        RACE = factor(RACE),
        SEX = factor(SEX)
    ) %>%
    select (Y, DOSE, AGE, SEX, RACE, WT, HT)

glimpse(model_data)
```

# Exploratory Data Analysis 
```{r}
# Check counts for categorical variables
model_data %>%
    count(SEX)

model_data %>%
    count(RACE)

model_data %>%
    count(DOSE)

# Obtain summary statistics.
summary(model_data)

# Obtain a more detailed summary 
model_data %>%
    summarise(
        mean_Y = mean(Y),
        sd_Y = sd(Y),
        mean_age = mean(AGE),
        mean_wt = mean(WT),
        mean_ht = mean(HT)
    )

# From this, we see that the outcome variable Y shows variabilty across individuals. These individuals were aged between 18 and 50, with predictors such as age, weight, and height appearing within normal adult ranges. 
```
```{r}
# Explore the relationship between Y and the predictors. n

# Age
ggplot(model_data, aes(x = AGE, y = Y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Total Drug (Y) vs Age") +
  theme_minimal()

# Dose. Visualize with a box plot, as it is categorical. 
ggplot(model_data, aes(x = factor(DOSE), y = Y)) +
  geom_boxplot() +
  labs(title = "Total Drug (Y) by Dose", x = "Dose") +
  theme_minimal()

# Height 
ggplot(model_data, aes(x = HT, y = Y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Total Drug (Y) vs Height") +
  theme_minimal()

# Race. Visualize with a box plot, as it is categorical. 
ggplot(model_data, aes(x = RACE, y = Y)) +
  geom_boxplot() +
  labs(title = "Total Drug (Y) by Race") +
  theme_minimal()

# Sex. Visualize with a box plot, as it is categorical. 
ggplot(model_data, aes(x = SEX, y = Y)) +
  geom_boxplot() +
  labs(title = "Total Drug (Y) by Sex") +
  theme_minimal()

# Weight 
ggplot(model_data, aes(x = WT, y = Y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Total Drug (Y) vs Weight") +
  theme_minimal()

# No strong linear relationships between Y and most predictors. The exception is dose, which suggests an increase in total drug exposure with higher doses (as expected).
```
```{r}
# View the distribution of variables to determine if there are any outliers. 

# Age
ggplot(model_data, aes(x = AGE)) +
  geom_histogram(bins = 20) +
  labs(title = "Age Distribution") +
  theme_minimal()

# Height 
ggplot(model_data, aes(x = HT)) +
  geom_histogram(bins = 20) +
  labs(title = "Height Distribution") +
  theme_minimal()

# Weight 
ggplot(model_data, aes(x = WT)) +
  geom_histogram(bins = 20) +
  labs(title = "Weight Distribution") +
  theme_minimal()

# Y 
ggplot(model_data, aes(x = Y)) +
  geom_histogram(bins = 30) +
  labs(title = "Distribution of Total Drug (Y)") +
  theme_minimal()

# No obvious, exxtreme outliers are visible. 
```

# Model Fitting

```{r}
# Fit a linear model where Y is predicted by dose

lm_dose <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Y ~ DOSE, data = model_data)

lm_dose_preds <- predict(lm_dose, model_data) %>%
  bind_cols(model_data)

metrics(lm_dose_preds, truth = Y, estimate = .pred)

# Fit a linear model to Y using all predictors 

lm_full <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Y ~ DOSE + AGE + SEX + RACE + WT + HT, data = model_data)

lm_full_preds <- predict(lm_full, model_data) %>%
  bind_cols(model_data)

metrics(lm_full_preds, truth = Y, estimate = .pred)

# These data indicate that there is a moderate relationship between dose and drug exposure. The R squared value indicates that dose alone explains >50% of the variability, while the RMSE of 666 indicates that the model's prediction deviate from the observed values by 666 units on average. 
```
```{r}
# Repeat the above, now considering sex as the outcome. 

# First, confirm that sex is a binary factor. 
model_data$SEX <- factor(model_data$SEX)

# Sex predicted by dose. 
log_dose <- logistic_reg() %>%
  set_engine("glm") %>%
  fit(SEX ~ DOSE, data = model_data)

log_dose_preds <- predict(log_dose, model_data, type = "prob") %>%
  bind_cols(predict(log_dose, model_data)) %>%
  bind_cols(model_data)

metrics(log_dose_preds, truth = SEX, estimate = .pred_class)
roc_auc(log_dose_preds, truth = SEX, .pred_1)

# These data indicate that dose alone does not predict sex. The Kappa statistic is 0, meaning that the model is not better than random guessing, and the ROC-AUC is 0.592, which indicates poor discriminatory ability / random classification. 

# Sex predicted by all predictors. 
log_full <- logistic_reg() %>%
  set_engine("glm") %>%
  fit(SEX ~ DOSE + AGE + RACE + WT + HT, data = model_data)

log_full_preds <- predict(log_full, model_data, type = "prob") %>%
  bind_cols(predict(log_full, model_data)) %>%
  bind_cols(model_data)

metrics(log_full_preds, truth = SEX, estimate = .pred_class)
roc_auc(log_full_preds, truth = SEX, .pred_1)

# These data indicate that variables such as weight and sex are correlated with sex. The Kappa value is 0.741 and the ROC-AUC is 0.975, indicating good model discrimination. 
```